### ISSUE TITLE
Lovelace not YAML mode - weblink or iframe support

### ISSUE THREAD

**Issue by antonakv** [azuwis/zigbee2mqtt-networkmap#22]
Please add weblink support to use plugin not in Lovelace YAML mode only.
For example it should be available by:
url: /local/zigbee2mqtt_networkmap/map.html

Thanks!

**Comment by azuwis** [comment]
For iframe you can use https://github.com/rgruebel/ha_zigbee2mqtt_networkmap

I wrote this because I want a normal lovelace custom card.

It's not YAML mode only, just like other lovelace custom card.  I wrote the YAML mode step in README because I don't use the default Lovelace UI, so I don't know the detail steps to use custom cards on them.

For more about how to use custom card, see https://developers.home-assistant.io/docs/lovelace_custom_card/

If you update the document and make pull requests, I'm more than happy to accept them.
