### ISSUE TITLE
FR - Zoom in/out

### ISSUE THREAD

**Issue by SeLLeRoNe** [azuwis/zigbee2mqtt-networkmap#9]
Hi,

Thanks for this card, it is very useful!
I would like to ask if it is possible to have a zoom in/out (+/-) button to better arrange the map

Right now, I can see most of the things but some are "out of view"
![image](https://user-images.githubusercontent.com/9599441/67095463-42e29c00-f1b6-11e9-8fe6-9950fa52652e.png)

Thanks!
Andrea

**Comment by SeLLeRoNe** [comment]
I have just noticed that there is actually an option to have a "larger view", but I still believe an "in card" ability to zoom in/out might be useful :)

**Comment by azuwis** [comment]
You can use the `force` option the change the view.

The force parameter can be dynamically changed, e.g. using 2 `+` `-` buttons. But the problem is that the changed value can not be easily saved, since this is a custom card not a custom component.

Zoom in/out function is on the todo list of https://github.com/emiliorizzo/vue-d3-network, which is the main display library zigbee2mqtt-networkmap is using.

**Comment by SeLLeRoNe** [comment]
Ok, thanks you for taking the time to respond :)

Let's wait it's done in the display library then ^^

Andrea
